INSERT INTO USER_LK(ID, NICK, LVL, LEARNT_WORDS) VALUES (99, 'sarah1', 'inter', 4);
INSERT INTO USER_LK(ID, NICK, LVL, LEARNT_WORDS) VALUES (100, 'kumar2', 'upper', 10);
INSERT INTO USER_LK(ID, NICK, LVL, LEARNT_WORDS) VALUES (101, 'user3', 'begginer', 1);
INSERT INTO USER_LK(ID, NICK, LVL, LEARNT_WORDS) VALUES (102, 'user4', 'inter', 3);